matrix:
  DOCKER_REPO:
    - ukhomeofficedigital/prometheus-load
  DOCKER_REGISTRY:
    - quay.io
  DOCKER_USERNAME:
    - ukhomeofficedigital+prometheus_load
  DOCKER_HOST:
    - tcp://172.17.0.1:2375
pipeline:
  docker-build:
    image: docker:19.03.12
    commands:
      - docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA} .
    when:
      event:
        - pull_request
        - push
        - tag

  docker-tag:
    image: docker:19.03.12
    environment:
      docker_username: ukhomeofficedigital+prometheus_load
    secrets:
      - docker_password
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
      - docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA} ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_TAG}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_TAG}
    when:
      event: tag

  docker-latest:
    image: docker:19.03.12
    environment:
      docker_username: ukhomeofficedigital+prometheus_load
    secrets:
      - docker_password
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p=$${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
      - docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA} ${DOCKER_REGISTRY}/${DOCKER_REPO}:latest
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:$${DRONE_COMMIT_SHA}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:latest
    when:
      event: push
      branch: master